version: '3.8'

services:
  crm-pocketbase-staging:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: crm-pocketbase-staging
    restart: unless-stopped
    volumes:
      - ./pocketbase/pb_data_staging:/pb_data
    ports:
      - "127.0.0.1:8091:8090"
    networks:
      - crm-staging

  crm-frontend-staging:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_POCKETBASE_URL=https://staging.crm.cguenther.app/pb
    container_name: crm-frontend-staging
    restart: unless-stopped
    environment:
      - POCKETBASE_URL=http://crm-pocketbase-staging:8090
      - NEXT_PUBLIC_POCKETBASE_URL=https://staging.crm.cguenther.app/pb
    ports:
      - "3101:3000"
    depends_on:
      - crm-pocketbase-staging
    networks:
      - crm-staging

networks:
  crm-staging:
    driver: bridge
